### ISSUE TITLE
Nested images are not added

### ISSUE THREAD

**Issue by larrykamau** [emperorDuke/nested_formdata#2]
Thanks for the awesome library💯🎉

In utils, NestedForms class, when converting and packaging the final data the

 `final_build.setdefault(key, root_tree) `

function does not add the final root tree

**Comment by samitnuk** [comment]
I believe that this can be fixed in a much better way (maybe in the `_group_data` method of `NestedForms` class), but in one of the projects I am working with I have "fixed" the issue by changing this line:
https://github.com/emperorDuke/nested_formdata/blob/d290752bc15cd2c10f37e058b332363183aee6ce/drf_nested_forms/utils.py#L141
to
```python
if key in final_build:
     final_build[key][0].update(root_tree[0])
else:
    final_build.setdefault(key, root_tree)
````

**Comment by emperorDuke** [comment]
Hello, sorry for the slow reply, could i see an example of the nested data with images sent, so as to be able to fixed the bug.

**Comment by samitnuk** [comment]
Hi @emperorDuke, Thanks for this lib 👍 

E.g. `FormData`:
```
user_address: 1
products[0][quantity]: 2
products[0][attributes][0][code]: color
products[0][attributes][0][value]: Pink
products[0][attributes][1][code]: size
products[0][attributes][1][value]: 6.0
products[0][attributes][2][code]: multi-pack
products[0][attributes][2][value]: No
products[0][images][0][image]: (binary)
products[0][images][1][image]: (binary)
products[0][images][2][image]: (binary)
products[0][images][3][image]: (binary)
products[0][images][4][image]: (binary)
```

Currently the `self._final_data` after the `__process__` method of `NestedForms` will be like:
```python
{
    'user_address': 1,
    'products': [
        {
            'quantity': 2,
            'attributes': [
                {'code': 'color', 'value': 'Pink'},
                {'code': 'size', 'value': '6.0'},
                {'code': 'multi-pack', 'value': 'No'}
            ],
        }
    ],
}
```
But it should be like:
```
{
    'user_address': 1,
    'products': [
        {
            'quantity': 2,
            'attributes': [
                {'code': 'color', 'value': 'Pink'},
                {'code': 'size', 'value': '6.0'},
                {'code': 'multi-pack', 'value': 'No'}
            ],
            'images': [
                {'image': <InMemoryUploadedFile: file0.jpg (image/jpeg)>},
                {'image': <InMemoryUploadedFile: file1.jpg (image/jpeg)>},
                {'image': <InMemoryUploadedFile: file2.jpg (image/jpeg)>},
                {'image': <InMemoryUploadedFile: file3.jpg (image/jpeg)>},
                {'image': <InMemoryUploadedFile: file4.jpg (image/jpeg)>},
            ]
        }
    ],
}
```
My "fix" does the job, but I think you will be able to create a better solution.

**Comment by emperorDuke** [comment]
I have fixed the bug try updating the library

**Comment by samitnuk** [comment]
Hi @emperorDuke,
Thanks a lot for the updated library. I have checked the last version and it still does not work for me for the nested images. The example of `FormData` I provided previously is a bit simplified version of the real `FormData` I am using. I think because of this the added test is not failing.

But if you add another line to the `data_2` (E.g. `'orderer': 1` after `'products[0][images][4][image]': ...`)
https://github.com/emperorDuke/nested_formdata/blob/568aa6f52837430346b13058ca59607d729b25a8/tests/test_app/tests.py#L11-L23
the test will fail since there will be no "images" in the view's `request.data`.

Will try to do more tests next week.

**Comment by samitnuk** [comment]
Just have found that "my fix" does not work properly if there are more than 1 "product".

So instead of (https://github.com/emperorDuke/nested_formdata/issues/2#issuecomment-854706017):
```python
if key in final_build:
     final_build[key][0].update(root_tree[0])
else:
    final_build.setdefault(key, root_tree)
```
now I use:
```python
if key in final_build:
    for idx in range(len(final_build[key])):
        final_build[key][idx].update(root_tree[idx])
else:
    final_build.setdefault(key, root_tree)
```

**Comment by emperorDuke** [comment]
Thanks, your fix doesn't cover some cases but the reason why the library breaks is because the nested form order breaks when parsed by the multipart parser. So if you move the "orderer" above "products"  the code will work.

**Comment by emperorDuke** [comment]
Thanks @samitnuk  for the help, Bug has been fixed try updating the library.

**Comment by samitnuk** [comment]
Hi @emperorDuke,

Just checked the latest version of the library (1.1.3) - now everything works as expected.

Many many thanks for your fast response and fix - your library is amazing! You are doing a great job! Many appreciations!
